### ISSUE TITLE
Exception ob zagonu skripte

### ISSUE THREAD

**Issue by matejhacin** [jamsix/ib-edavki#135]
Pozdravljeni,

Ob zagonu `ib_edavki /Users/matejh/Downloads/tax_2021.xml /Users/matejh/Downloads/tax_2022.xml /Users/matejh/Downloads/tax_2023.xml /Users/matejh/Downloads/tax_2024.xml` debim sledeč error stacktrace:

<img width="1147" alt="Screenshot 2024-05-02 at 11 07 34" src="https://github.com/jamsix/ib-edavki/assets/10889496/f6ae00ea-1e7d-40af-a4e7-67707ce17fb8">

Poizkusil sem tudi z drugačnimi parametri kot npr. `ib_edavki tax_2021` ali `ib_edavki /Users/matejh/Downloads/tax_2021.xml` ampak vedno dobim isti error.

Nekaj dodatnih informacij:
- Python 3.12.2
- macOS Sonoma 14.4.1
- git version 2.39.3

**Comment by jamsix** [comment]
Python pravi, da ne zna preverit certifikata https://github.com/jamsix/ib-edavki/raw/master/companies.xml

Verjetno si za kakim TLS decrypting proxyjem. Služben laptop?

Poskusi `curl -vvv https://github.com/jamsix/ib-edavki/raw/master/companies.xml`

**Comment by jamsix** [comment]
Kot kaže `requests` v pythonu ne uporablja sistemskega CA stora. Poskusi še `pip install certifi --upgrade`

**Comment by sasos90** [comment]
Tudi meni se isto dogaja. Nimam nobenih proxyjev itd.

**Comment by jamsix** [comment]
@sasos90 tvoj problem je drugačen. bsi.si strežnik po novem ne sprejema zahtevkov brez ustreznega `User-Agent` stringa. Popravljeno v https://github.com/jamsix/ib-edavki/pull/137 in bo na voljo v kratkem.

**Comment by sasos90** [comment]
@jamsix super! hvala!

**Comment by sasos90** [comment]
Hm, sedaj dobim tole:
```
$ ib_edavki.exe ib-xml-file-2024.xml
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\saso\AppData\Local\Programs\Python\Python312\Scripts\ib_edavki.exe\__main__.py", line 4, in <module>
  File "C:\Users\saso\AppData\Local\Programs\Python\Python312\Lib\site-packages\ib_edavki.py", line 10, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by jamsix** [comment]
OK, si zrihtal. Moram dodat `requests` v `setup.py`

**Comment by Hrastopow** [comment]
Oj, jaz imam isti problem in sicer, da ob tem, ko dodam parameter -t, dobim sledeči error. Brez parametra -t deluje OK. Kaj bi lahko bilo narobe? 
![Uploading error_ibkrscript.jpg…]()

**Comment by Hrastopow** [comment]
Mi je uspelo rešiti, če bo imel še kdo podobno težavo. Pod Applications -> Python se nahaja skripta "Install Certificates.command". Double klik in požene skripto. Po tem več ni vrglo napake :)
