### ISSUE TITLE
ModuleNotFoundError: No module named 'generators'

### ISSUE THREAD

**Issue by tomazb** [jamsix/ib-edavki#24]
On Fedora 32

Traceback (most recent call last):
  File "/usr/local/bin/ib-edavki", line 11, in <module>
    load_entry_point('ib-edavki==1.4.0', 'console_scripts', 'ib-edavki')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/site-packages/ib_edavki.py", line 14, in <module>
    from generators import doh_obr
ModuleNotFoundError: No module named 'generators'

On Ubuntu20 LTS:
Traceback (most recent call last):
  File "/usr/local/bin/ib-edavki", line 5, in <module>
    from ib_edavki import main
  File "/home/tomaz/.local/lib/python3.8/site-packages/ib_edavki.py", line 14, in <module>
    from generators import doh_obr
ModuleNotFoundError: No module named 'generators'

**Comment by ddbk** [comment]
The issue was introduced with #22 . I prepared a fix in the linked pull request but maybe someone else can also check if module loading now works as intended as I'm not python native. :)

**Comment by jamsix** [comment]
Works for me, let us know @tomazb

**Comment by tomazb** [comment]
Already tested on Ubuntu where it works for sure. Seems ok on Fedora 32 as well. Thank you.
