### ISSUE TITLE
Error delam kaj narobe ?

### ISSUE THREAD

**Issue by gex12** [jamsix/ib-edavki#71]
Lani mi je uspelo narediti report za 2021, letos pa za 2022 dobim sledeči error. Sem še enkrat nardil za 2021 pa dela vse normalno, pri 2022 reportu se pa vedno zatakne. Tako, da če kdo ve kaj delam narobe

C:\Users\123456 (vse)\Desktop\ib-edavki-master>ib_edavki.py -y 2022 edavki_2021.xml edavki_2022.xml
Traceback (most recent call last):
  File "C:\Users\123456 (vse)\Desktop\ib-edavki-master\ib_edavki.py", line 1344, in <module>
    main()
  File "C:\Users\123456 (vse)\Desktop\ib-edavki-master\ib_edavki.py", line 260, in main
    addStockSplits(corporateActions)
  File "C:\Users\123456 (vse)\Desktop\ib-edavki-master\ib_edavki.py", line 46, in addStockSplits
    multiplier = float(descriptionSearch.group(1)) / float(
                                                     ^^^^^^
ValueError: could not convert string to float: '1 (ML, MICHELIN'

C:\Users\123456 (vse)\Desktop\ib-edavki-master>

**Comment by jamsix** [comment]
Verjetno bug. Lahko prilepiš vse `<CorporateAction>` vrstice iz tvojega XMLja, ki vsebujejo Michelin?

**Comment by jamsix** [comment]
Oz, zna bit da je https://github.com/jamsix/ib-edavki/pull/69 popravil tvoj problem. Lahko updataš `ib-edavki` na zadnjo verzijo in poskusiš znova?

**Comment by gex12** [comment]
Še kr dobim enako napako. Upam, je to kar si mislil, ker se glih ne spoznam na te stvari.

<CorporateAction accountId="U7000046" acctAlias="" model="" currency="EUR" fxRateToBase="1" assetCategory="STK" symbol="ML" description="ML(FR0000121261) SPLIT 4 FOR 1 (ML, MICHELIN (CGDE), FR001400AJ45)" conid="562418770" securityID="FR001400AJ45" securityIDType="ISIN" cusip="" isin="FR001400AJ45" listingExchange="SBF" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" putCall="" principalAdjustFactor="" reportDate="20220616" dateTime="20220615;202500" actionDescription="ML(FR0000121261) SPLIT 4 FOR 1 (ML, MICHELIN (CGDE), FR001400AJ45)" amount="0" proceeds="0" value="0" quantity="12" fifoPnlRealized="0" mtmPnl="0" code="" type="FI" transactionID="314461182" actionID="108230866" levelOfDetail="DETAIL" serialNumber="" deliveryType="" commodityType="" fineness="0.0" weight="0.0 ()" />

<CorporateAction accountId="U7000046" acctAlias="" model="" currency="EUR" fxRateToBase="1" assetCategory="STK" symbol="ML.OLD" description="ML(FR0000121261) SPLIT 4 FOR 1 (ML.OLD, MICHELIN (CGDE), FR0000121261)" conid="29612156" securityID="FR0000121261" securityIDType="ISIN" cusip="" isin="FR0000121261" listingExchange="SBF" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" putCall="" principalAdjustFactor="" reportDate="20220616" dateTime="20220615;202500" actionDescription="ML(FR0000121261) SPLIT 4 FOR 1 (ML.OLD, MICHELIN (CGDE), FR0000121261)" amount="0" proceeds="0" value="0" quantity="-3" fifoPnlRealized="0" mtmPnl="0" code="" type="FI" transactionID="314461181" actionID="108230866" levelOfDetail="DETAIL" serialNumber="" deliveryType="" commodityType="" fineness="0.0" weight="0.0 ()" />

**Comment by gex12** [comment]
<CorporateAction accountId="U7000046" acctAlias="" model="" currency="EUR" fxRateToBase="1" assetCategory="STK" symbol="ML" description="ML(FR0000121261) SPLIT 4 FOR 1 (ML, MICHELIN (CGDE), FR001400AJ45)" conid="562418770" securityID="FR001400AJ45" securityIDType="ISIN" cusip="" isin="FR001400AJ45" listingExchange="SBF" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" putCall="" principalAdjustFactor="" reportDate="20220616" dateTime="20220615;202500" actionDescription="ML(FR0000121261) SPLIT 4 FOR 1 (ML, MICHELIN (CGDE), FR001400AJ45)" amount="0" proceeds="0" value="0" quantity="12" fifoPnlRealized="0" mtmPnl="0" code="" type="FI" transactionID="314461182" actionID="108230866" levelOfDetail="DETAIL" serialNumber="" deliveryType="" commodityType="" fineness="0.0" weight="0.0 ()" />
<CorporateAction accountId="U7000046" acctAlias="" model="" currency="EUR" fxRateToBase="1" assetCategory="STK" symbol="ML.OLD" description="ML(FR0000121261) SPLIT 4 FOR 1 (ML.OLD, MICHELIN (CGDE), FR0000121261)" conid="29612156" securityID="FR0000121261" securityIDType="ISIN" cusip="" isin="FR0000121261" listingExchange="SBF" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" putCall="" principalAdjustFactor="" reportDate="20220616" dateTime="20220615;202500" actionDescription="ML(FR0000121261) SPLIT 4 FOR 1 (ML.OLD, MICHELIN (CGDE), FR0000121261)" amount="0" proceeds="0" value="0" quantity="-3" fifoPnlRealized="0" mtmPnl="0" code="" type="FI" transactionID="314461181" actionID="108230866" levelOfDetail="DETAIL" serialNumber="" deliveryType="" commodityType="" fineness="0.0" weight="0.0 ()" />

**Comment by gex12** [comment]
<CorporateAction accountId="U7000046" acctAlias="" model="" currency="EUR" fxRateToBase="1" assetCategory="STK" symbol="ML" description="ML(FR0000121261) SPLIT 4 FOR 1 (ML, MICHELIN (CGDE), FR001400AJ45)" conid="562418770" securityID="FR001400AJ45" securityIDType="ISIN" cusip="" isin="FR001400AJ45" listingExchange="SBF" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" putCall="" principalAdjustFactor="" reportDate="20220616" dateTime="20220615;202500" actionDescription="ML(FR0000121261) SPLIT 4 FOR 1 (ML, MICHELIN (CGDE), FR001400AJ45)" amount="0" proceeds="0" value="0" quantity="12" fifoPnlRealized="0" mtmPnl="0" code="" type="FI" transactionID="314461182" actionID="108230866" levelOfDetail="DETAIL" serialNumber="" deliveryType="" commodityType="" fineness="0.0" weight="0.0 ()" />

<CorporateAction accountId="U7000046" acctAlias="" model="" currency="EUR" fxRateToBase="1" assetCategory="STK" symbol="ML.OLD" description="ML(FR0000121261) SPLIT 4 FOR 1 (ML.OLD, MICHELIN (CGDE), FR0000121261)" conid="29612156" securityID="FR0000121261" securityIDType="ISIN" cusip="" isin="FR0000121261" listingExchange="SBF" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" putCall="" principalAdjustFactor="" reportDate="20220616" dateTime="20220615;202500" actionDescription="ML(FR0000121261) SPLIT 4 FOR 1 (ML.OLD, MICHELIN (CGDE), FR0000121261)" amount="0" proceeds="0" value="0" quantity="-3" fifoPnlRealized="0" mtmPnl="0" code="" type="FI" transactionID="314461181" actionID="108230866" levelOfDetail="DETAIL" serialNumber="" deliveryType="" commodityType="" fineness="0.0" weight="0.0 ()" />

**Comment by gex12** [comment]
`<CorporateAction accountId="U7000046" acctAlias="" model="" currency="EUR" fxRateToBase="1" assetCategory="STK" symbol="ML" description="ML(FR0000121261) SPLIT 4 FOR 1 (ML, MICHELIN (CGDE), FR001400AJ45)" conid="562418770" securityID="FR001400AJ45" securityIDType="ISIN" cusip="" isin="FR001400AJ45" listingExchange="SBF" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" putCall="" principalAdjustFactor="" reportDate="20220616" dateTime="20220615;202500" actionDescription="ML(FR0000121261) SPLIT 4 FOR 1 (ML, MICHELIN (CGDE), FR001400AJ45)" amount="0" proceeds="0" value="0" quantity="12" fifoPnlRealized="0" mtmPnl="0" code="" type="FI" transactionID="314461182" actionID="108230866" levelOfDetail="DETAIL" serialNumber="" deliveryType="" commodityType="" fineness="0.0" weight="0.0 ()" />
<CorporateAction accountId="U7000046" acctAlias="" model="" currency="EUR" fxRateToBase="1" assetCategory="STK" symbol="ML.OLD" description="ML(FR0000121261) SPLIT 4 FOR 1 (ML.OLD, MICHELIN (CGDE), FR0000121261)" conid="29612156" securityID="FR0000121261" securityIDType="ISIN" cusip="" isin="FR0000121261" listingExchange="SBF" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" putCall="" principalAdjustFactor="" reportDate="20220616" dateTime="20220615;202500" actionDescription="ML(FR0000121261) SPLIT 4 FOR 1 (ML.OLD, MICHELIN (CGDE), FR0000121261)" amount="0" proceeds="0" value="0" quantity="-3" fifoPnlRealized="0" mtmPnl="0" code="" type="FI" transactionID="314461181" actionID="108230866" levelOfDetail="DETAIL" serialNumber="" deliveryType="" commodityType="" fineness="0.0" weight="0.0 ()" />`

**Comment by jamsix** [comment]
OK, preverim, samo ta teden mi ne bo zneslo. Bo pa zrihtano pred koncem februarja. Če se ti mudi, samo odstrani ti dve vrstici preden poženeš `ib-edavki` ter morebitne prodaje `ML` dodaj na roke.
