### ISSUE TITLE
KeyError: 'assetType'

### ISSUE THREAD

**Issue by pronebird** [jamsix/ib-edavki#82]
Breaks down with the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/ib-edavki", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/ib_edavki.py", line 570, in main
    if trade["assetType"] == "normal" and trade["positionType"] == "long":
KeyError: 'assetType'
```

**Comment by jamsix** [comment]
Yes, should be easy, just add `FXCFD` to these 3 lines:

https://github.com/jamsix/ib-edavki/blob/233acbbcf6d96e058f6306e39f12a897aac2ad6d/ib_edavki.py#L20
https://github.com/jamsix/ib-edavki/blob/233acbbcf6d96e058f6306e39f12a897aac2ad6d/ib_edavki.py#L909
https://github.com/jamsix/ib-edavki/blob/233acbbcf6d96e058f6306e39f12a897aac2ad6d/ib_edavki.py#L997

Will you do the PR?

**Comment by pronebird** [comment]
@jamsix thanks, figured that out. PR: https://github.com/jamsix/ib-edavki/pull/83
